import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/src/components/ui/sonner";
import {Toaster as ToasterForToast} from "@/src/components/ui/toaster";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth";
import React from "react";
import {SidebarProvider} from "@/src/components/ui/sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth();
    console.log(session);
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SessionProvider>
            <SidebarProvider>
                {children}
            </SidebarProvider>
            <ToasterForToast />
            <Toaster/>
        </SessionProvider>
        </body>
        </html>
    );
}
